{
    "Message": "Upload in progress...",
    "CompletionMessage": "Upload Successful",
    "CompletionTimeout": 7,
    "OnSuccess": "/ProductCatalog2/Actions/Service/UploadOffline.action",
    "OnFailure": "/ProductCatalog2/Actions/Service/SyncFailureMessage.action",
    "_Type": "Action.Type.ProgressBanner"
}